#ARG CUDA_VER='11.2.1'
ARG CUDA_VER='11.1.1'
FROM nvidia/cuda:${CUDA_VER}-devel-ubuntu20.04
#==============================================================================
ARG TORCH_UCC_ROOT_DIR=/opt/nvidia/torch-ucc
ENV TORCH_UCC_SRC_DIR=${TORCH_UCC_ROOT_DIR}/src
ENV TORCH_UCC_PKG_DIR=${TORCH_UCC_ROOT_DIR}/pkg
ENV TORCH_UCC_BIN_DIR=${TORCH_UCC_ROOT_DIR}/bin
ENV TORCH_UCC_WORKLOADS_DIR=${TORCH_UCC_ROOT_DIR}/workloads
ENV CUDA_HOME=/usr/local/cuda
ENV UCX_BRANCH=v1.10.x
ENV UCX_BUILD_TYPE=release-mt
ENV UCX_INSTALL_DIR=${TORCH_UCC_BIN_DIR}/ucx/build-${UCX_BUILD_TYPE}
ENV XCCL_BUILD_TYPE=debug
ENV XCCL_INSTALL_DIR=${TORCH_UCC_BIN_DIR}/xccl/build-${XCCL_BUILD_TYPE}
#==============================================================================
RUN mkdir -p ${TORCH_UCC_SRC_DIR} && \
    mkdir -p ${TORCH_UCC_PKG_DIR} && \
    mkdir -p ${TORCH_UCC_BIN_DIR} && \
    mkdir -p ${TORCH_UCC_WORKLOADS_DIR}

COPY . ${TORCH_UCC_SRC_DIR}
#==============================================================================
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && \
    apt install -y \
        apt-utils \
        autoconf \
        build-essential \
        cmake \
        curl \
        git \
        ibverbs-providers \
        ibverbs-utils \
        libnuma-dev \
        libtool-bin \
        ninja-build \
        openmpi-bin \
        openssh-server \
        vim \
    && \
    rm -rf /var/lib/apt/lists/*
#==============================================================================
# Configure SSH
RUN mkdir -p /var/run/sshd && \
    cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new && \
    echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new && \
    mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config
#==============================================================================
# Build UCX
RUN ${TORCH_UCC_SRC_DIR}/.ci/scripts/build_ucx.sh
ENV PATH=${UCX_INSTALL_DIR}/bin:${PATH}
#==============================================================================
# Configure Python
RUN ${TORCH_UCC_SRC_DIR}/.ci/scripts/configure_python.sh
ENV PATH /opt/conda/bin:${PATH}
#==============================================================================
# Build XCCL
RUN ${TORCH_UCC_SRC_DIR}/.ci/scripts/build_xccl.sh
#==============================================================================
# Install PyTorch
RUN ${TORCH_UCC_SRC_DIR}/.ci/scripts/install_torch.sh
#==============================================================================
# Install torch_ucc python module and build a wheel package
RUN ${TORCH_UCC_SRC_DIR}/.ci/scripts/install_torch_ucc.sh
#==============================================================================
# Install workloads
WORKDIR ${TORCH_UCC_WORKLOADS_DIR}
RUN git clone https://github.com/facebookresearch/dlrm.git && \
    cd ${TORCH_UCC_WORKLOADS_DIR}/dlrm && \
    git apply ${TORCH_UCC_SRC_DIR}/.ci/patches/dlrm/0001-Added-torch_ucc-support.patch && \
    pip install -r ${TORCH_UCC_WORKLOADS_DIR}/dlrm/requirements.txt && \
    pip install tensorboard
RUN git clone https://github.com/facebookresearch/param.git && \
    pip install -r ${TORCH_UCC_WORKLOADS_DIR}/param/requirements.txt