name: Clang-format Full Tree
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.8
      with:
        source: '.'
        extensions: 'hpp,cpp'
        clangFormatVersion: 8
        style: file
